openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://127.0.0.1:8900'
    description: Generated server url
paths:
  /ping:
    get:
      tags:
        - Ping
      description: ping通测试API
      operationId: ping
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
            default: pong
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string

components: {}